apiVersion: v2
name: varpulis-cluster
description: Varpulis CEP distributed cluster - coordinator + workers
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - cep
  - streaming
  - analytics
  - distributed
home: https://github.com/varpulis/varpulis
maintainers:
  - name: Varpulis Team
