apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: varpulis-k3d
namePrefix: k3d-

resources:
  - ../../base

patches:
  - path: deployment-patch.yaml
  - path: service-patch.yaml
  - path: coordinator-patch.yaml

images:
  - name: varpulis/varpulis
    newName: varpulis-local
    newTag: latest
